//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	k8sv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAddressIdentity) DeepCopyInto(out *ExternalAddressIdentity) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(ExternalAddressParent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAddressIdentity.
func (in *ExternalAddressIdentity) DeepCopy() *ExternalAddressIdentity {
	if in == nil {
		return nil
	}
	out := new(ExternalAddressIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAddressParent) DeepCopyInto(out *ExternalAddressParent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAddressParent.
func (in *ExternalAddressParent) DeepCopy() *ExternalAddressParent {
	if in == nil {
		return nil
	}
	out := new(ExternalAddressParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAddressRef) DeepCopyInto(out *ExternalAddressRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAddressRef.
func (in *ExternalAddressRef) DeepCopy() *ExternalAddressRef {
	if in == nil {
		return nil
	}
	out := new(ExternalAddressRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicy_NetworkService) DeepCopyInto(out *NetworkPolicy_NetworkService) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy_NetworkService.
func (in *NetworkPolicy_NetworkService) DeepCopy() *NetworkPolicy_NetworkService {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy_NetworkService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicy_NetworkServiceObservedState) DeepCopyInto(out *NetworkPolicy_NetworkServiceObservedState) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy_NetworkServiceObservedState.
func (in *NetworkPolicy_NetworkServiceObservedState) DeepCopy() *NetworkPolicy_NetworkServiceObservedState {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy_NetworkServiceObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareEngineExternalAddress) DeepCopyInto(out *VMwareEngineExternalAddress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareEngineExternalAddress.
func (in *VMwareEngineExternalAddress) DeepCopy() *VMwareEngineExternalAddress {
	if in == nil {
		return nil
	}
	out := new(VMwareEngineExternalAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMwareEngineExternalAddress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareEngineExternalAddressList) DeepCopyInto(out *VMwareEngineExternalAddressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMwareEngineExternalAddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareEngineExternalAddressList.
func (in *VMwareEngineExternalAddressList) DeepCopy() *VMwareEngineExternalAddressList {
	if in == nil {
		return nil
	}
	out := new(VMwareEngineExternalAddressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMwareEngineExternalAddressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareEngineExternalAddressObservedState) DeepCopyInto(out *VMwareEngineExternalAddressObservedState) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.ExternalIP != nil {
		in, out := &in.ExternalIP, &out.ExternalIP
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareEngineExternalAddressObservedState.
func (in *VMwareEngineExternalAddressObservedState) DeepCopy() *VMwareEngineExternalAddressObservedState {
	if in == nil {
		return nil
	}
	out := new(VMwareEngineExternalAddressObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareEngineExternalAddressSpec) DeepCopyInto(out *VMwareEngineExternalAddressSpec) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareEngineExternalAddressSpec.
func (in *VMwareEngineExternalAddressSpec) DeepCopy() *VMwareEngineExternalAddressSpec {
	if in == nil {
		return nil
	}
	out := new(VMwareEngineExternalAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareEngineExternalAddressStatus) DeepCopyInto(out *VMwareEngineExternalAddressStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1beta1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(VMwareEngineExternalAddressObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareEngineExternalAddressStatus.
func (in *VMwareEngineExternalAddressStatus) DeepCopy() *VMwareEngineExternalAddressStatus {
	if in == nil {
		return nil
	}
	out := new(VMwareEngineExternalAddressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmwareEngineNetwork_VpcNetwork) DeepCopyInto(out *VmwareEngineNetwork_VpcNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmwareEngineNetwork_VpcNetwork.
func (in *VmwareEngineNetwork_VpcNetwork) DeepCopy() *VmwareEngineNetwork_VpcNetwork {
	if in == nil {
		return nil
	}
	out := new(VmwareEngineNetwork_VpcNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmwareEngineNetwork_VpcNetworkObservedState) DeepCopyInto(out *VmwareEngineNetwork_VpcNetworkObservedState) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmwareEngineNetwork_VpcNetworkObservedState.
func (in *VmwareEngineNetwork_VpcNetworkObservedState) DeepCopy() *VmwareEngineNetwork_VpcNetworkObservedState {
	if in == nil {
		return nil
	}
	out := new(VmwareEngineNetwork_VpcNetworkObservedState)
	in.DeepCopyInto(out)
	return out
}
