//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupInfo) DeepCopyInto(out *BackupInfo) {
	*out = *in
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.SourceTable != nil {
		in, out := &in.SourceTable, &out.SourceTable
		*out = new(string)
		**out = **in
	}
	if in.SourceBackup != nil {
		in, out := &in.SourceBackup, &out.SourceBackup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupInfo.
func (in *BackupInfo) DeepCopy() *BackupInfo {
	if in == nil {
		return nil
	}
	out := new(BackupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableInstance) DeepCopyInto(out *BigtableInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableInstance.
func (in *BigtableInstance) DeepCopy() *BigtableInstance {
	if in == nil {
		return nil
	}
	out := new(BigtableInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BigtableInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableInstanceList) DeepCopyInto(out *BigtableInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BigtableInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableInstanceList.
func (in *BigtableInstanceList) DeepCopy() *BigtableInstanceList {
	if in == nil {
		return nil
	}
	out := new(BigtableInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BigtableInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableInstanceSpec) DeepCopyInto(out *BigtableInstanceSpec) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.DeletionProtection != nil {
		in, out := &in.DeletionProtection, &out.DeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.InstanceType != nil {
		in, out := &in.InstanceType, &out.InstanceType
		*out = new(string)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = make([]InstanceCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableInstanceSpec.
func (in *BigtableInstanceSpec) DeepCopy() *BigtableInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(BigtableInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableInstanceStatus) DeepCopyInto(out *BigtableInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableInstanceStatus.
func (in *BigtableInstanceStatus) DeepCopy() *BigtableInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(BigtableInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableTable) DeepCopyInto(out *BigtableTable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableTable.
func (in *BigtableTable) DeepCopy() *BigtableTable {
	if in == nil {
		return nil
	}
	out := new(BigtableTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BigtableTable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableTableList) DeepCopyInto(out *BigtableTableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BigtableTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableTableList.
func (in *BigtableTableList) DeepCopy() *BigtableTableList {
	if in == nil {
		return nil
	}
	out := new(BigtableTableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableTableObservedState) DeepCopyInto(out *BigtableTableObservedState) {
	*out = *in
	if in.ClusterStates != nil {
		in, out := &in.ClusterStates, &out.ClusterStates
		*out = make(map[string]TableClusterState, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.RestoreInfo != nil {
		in, out := &in.RestoreInfo, &out.RestoreInfo
		*out = new(RestoreInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableTableObservedState.
func (in *BigtableTableObservedState) DeepCopy() *BigtableTableObservedState {
	if in == nil {
		return nil
	}
	out := new(BigtableTableObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableTableSpec) DeepCopyInto(out *BigtableTableSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableTableSpec.
func (in *BigtableTableSpec) DeepCopy() *BigtableTableSpec {
	if in == nil {
		return nil
	}
	out := new(BigtableTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigtableTableStatus) DeepCopyInto(out *BigtableTableStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ClusterStates != nil {
		in, out := &in.ClusterStates, &out.ClusterStates
		*out = make(map[string]ClusterState, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.RestoreInfo != nil {
		in, out := &in.RestoreInfo, &out.RestoreInfo
		*out = new(RestoreInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigtableTableStatus.
func (in *BigtableTableStatus) DeepCopy() *BigtableTableStatus {
	if in == nil {
		return nil
	}
	out := new(BigtableTableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeStreamConfig) DeepCopyInto(out *ChangeStreamConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeStreamConfig.
func (in *ChangeStreamConfig) DeepCopy() *ChangeStreamConfig {
	if in == nil {
		return nil
	}
	out := new(ChangeStreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterState) DeepCopyInto(out *ClusterState) {
	*out = *in
	if in.ReplicationState != nil {
		in, out := &in.ReplicationState, &out.ReplicationState
		*out = new(string)
		**out = **in
	}
	if in.EncryptionInfo != nil {
		in, out := &in.EncryptionInfo, &out.EncryptionInfo
		*out = make([]EncryptionInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterState.
func (in *ClusterState) DeepCopy() *ClusterState {
	if in == nil {
		return nil
	}
	out := new(ClusterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnFamily) DeepCopyInto(out *ColumnFamily) {
	*out = *in
	if in.GcRule != nil {
		in, out := &in.GcRule, &out.GcRule
		*out = new(GcRule)
		(*in).DeepCopyInto(*out)
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(Type)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnFamily.
func (in *ColumnFamily) DeepCopy() *ColumnFamily {
	if in == nil {
		return nil
	}
	out := new(ColumnFamily)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionInfo) DeepCopyInto(out *EncryptionInfo) {
	*out = *in
	if in.EncryptionType != nil {
		in, out := &in.EncryptionType, &out.EncryptionType
		*out = new(string)
		**out = **in
	}
	if in.KmsKeyVersion != nil {
		in, out := &in.KmsKeyVersion, &out.KmsKeyVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionInfo.
func (in *EncryptionInfo) DeepCopy() *EncryptionInfo {
	if in == nil {
		return nil
	}
	out := new(EncryptionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcRule) DeepCopyInto(out *GcRule) {
	*out = *in
	if in.MaxNumVersions != nil {
		in, out := &in.MaxNumVersions, &out.MaxNumVersions
		*out = new(int32)
		**out = **in
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(string)
		**out = **in
	}
	if in.Intersection != nil {
		in, out := &in.Intersection, &out.Intersection
		*out = new(GcRuleIntersection)
		(*in).DeepCopyInto(*out)
	}
	if in.Union != nil {
		in, out := &in.Union, &out.Union
		*out = new(GcRuleUnion)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcRule.
func (in *GcRule) DeepCopy() *GcRule {
	if in == nil {
		return nil
	}
	out := new(GcRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcRuleIntersection) DeepCopyInto(out *GcRuleIntersection) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]GcRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcRuleIntersection.
func (in *GcRuleIntersection) DeepCopy() *GcRuleIntersection {
	if in == nil {
		return nil
	}
	out := new(GcRuleIntersection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcRuleUnion) DeepCopyInto(out *GcRuleUnion) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]GcRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcRuleUnion.
func (in *GcRuleUnion) DeepCopy() *GcRuleUnion {
	if in == nil {
		return nil
	}
	out := new(GcRuleUnion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceAutoscalingConfig) DeepCopyInto(out *InstanceAutoscalingConfig) {
	*out = *in
	if in.StorageTarget != nil {
		in, out := &in.StorageTarget, &out.StorageTarget
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceAutoscalingConfig.
func (in *InstanceAutoscalingConfig) DeepCopy() *InstanceAutoscalingConfig {
	if in == nil {
		return nil
	}
	out := new(InstanceAutoscalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceCluster) DeepCopyInto(out *InstanceCluster) {
	*out = *in
	if in.AutoscalingConfig != nil {
		in, out := &in.AutoscalingConfig, &out.AutoscalingConfig
		*out = new(InstanceAutoscalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KmsKeyRef != nil {
		in, out := &in.KmsKeyRef, &out.KmsKeyRef
		*out = new(refsv1beta1.KMSCryptoKeyRef)
		**out = **in
	}
	if in.NumNodes != nil {
		in, out := &in.NumNodes, &out.NumNodes
		*out = new(int64)
		**out = **in
	}
	if in.StorageType != nil {
		in, out := &in.StorageType, &out.StorageType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceCluster.
func (in *InstanceCluster) DeepCopy() *InstanceCluster {
	if in == nil {
		return nil
	}
	out := new(InstanceCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreInfo) DeepCopyInto(out *RestoreInfo) {
	*out = *in
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(string)
		**out = **in
	}
	if in.BackupInfo != nil {
		in, out := &in.BackupInfo, &out.BackupInfo
		*out = new(BackupInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreInfo.
func (in *RestoreInfo) DeepCopy() *RestoreInfo {
	if in == nil {
		return nil
	}
	out := new(RestoreInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableAutomatedBackupPolicy) DeepCopyInto(out *TableAutomatedBackupPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableAutomatedBackupPolicy.
func (in *TableAutomatedBackupPolicy) DeepCopy() *TableAutomatedBackupPolicy {
	if in == nil {
		return nil
	}
	out := new(TableAutomatedBackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableClusterState) DeepCopyInto(out *TableClusterState) {
	*out = *in
	if in.ReplicationState != nil {
		in, out := &in.ReplicationState, &out.ReplicationState
		*out = new(string)
		**out = **in
	}
	if in.EncryptionInfo != nil {
		in, out := &in.EncryptionInfo, &out.EncryptionInfo
		*out = make([]EncryptionInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableClusterState.
func (in *TableClusterState) DeepCopy() *TableClusterState {
	if in == nil {
		return nil
	}
	out := new(TableClusterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableIdentity) DeepCopyInto(out *TableIdentity) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(TableParent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableIdentity.
func (in *TableIdentity) DeepCopy() *TableIdentity {
	if in == nil {
		return nil
	}
	out := new(TableIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableParent) DeepCopyInto(out *TableParent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableParent.
func (in *TableParent) DeepCopy() *TableParent {
	if in == nil {
		return nil
	}
	out := new(TableParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableRef) DeepCopyInto(out *TableRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableRef.
func (in *TableRef) DeepCopy() *TableRef {
	if in == nil {
		return nil
	}
	out := new(TableRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Type) DeepCopyInto(out *Type) {
	*out = *in
	if in.BytesType != nil {
		in, out := &in.BytesType, &out.BytesType
		*out = new(TypeBytes)
		(*in).DeepCopyInto(*out)
	}
	if in.StringType != nil {
		in, out := &in.StringType, &out.StringType
		*out = new(TypeString)
		(*in).DeepCopyInto(*out)
	}
	if in.Int64Type != nil {
		in, out := &in.Int64Type, &out.Int64Type
		*out = new(TypeInt64)
		(*in).DeepCopyInto(*out)
	}
	if in.Float32Type != nil {
		in, out := &in.Float32Type, &out.Float32Type
		*out = new(TypeFloat32)
		**out = **in
	}
	if in.Float64Type != nil {
		in, out := &in.Float64Type, &out.Float64Type
		*out = new(TypeFloat64)
		**out = **in
	}
	if in.BoolType != nil {
		in, out := &in.BoolType, &out.BoolType
		*out = new(TypeBool)
		**out = **in
	}
	if in.TimestampType != nil {
		in, out := &in.TimestampType, &out.TimestampType
		*out = new(TypeTimestamp)
		**out = **in
	}
	if in.DateType != nil {
		in, out := &in.DateType, &out.DateType
		*out = new(TypeDate)
		**out = **in
	}
	if in.AggregateType != nil {
		in, out := &in.AggregateType, &out.AggregateType
		*out = new(TypeAggregate)
		(*in).DeepCopyInto(*out)
	}
	if in.StructType != nil {
		in, out := &in.StructType, &out.StructType
		*out = new(TypeStruct)
		(*in).DeepCopyInto(*out)
	}
	if in.ArrayType != nil {
		in, out := &in.ArrayType, &out.ArrayType
		*out = new(TypeArray)
		(*in).DeepCopyInto(*out)
	}
	if in.MapType != nil {
		in, out := &in.MapType, &out.MapType
		*out = new(TypeMap)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Type.
func (in *Type) DeepCopy() *Type {
	if in == nil {
		return nil
	}
	out := new(Type)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeAggregate) DeepCopyInto(out *TypeAggregate) {
	*out = *in
	if in.InputType != nil {
		in, out := &in.InputType, &out.InputType
		*out = new(Type)
		(*in).DeepCopyInto(*out)
	}
	if in.StateType != nil {
		in, out := &in.StateType, &out.StateType
		*out = new(Type)
		(*in).DeepCopyInto(*out)
	}
	if in.Sum != nil {
		in, out := &in.Sum, &out.Sum
		*out = new(TypeAggregateSum)
		**out = **in
	}
	if in.HllppUniqueCount != nil {
		in, out := &in.HllppUniqueCount, &out.HllppUniqueCount
		*out = new(TypeAggregateHllppUniqueCount)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(TypeAggregateMax)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(TypeAggregateMin)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeAggregate.
func (in *TypeAggregate) DeepCopy() *TypeAggregate {
	if in == nil {
		return nil
	}
	out := new(TypeAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeAggregateHLLPPUniqueCount) DeepCopyInto(out *TypeAggregateHLLPPUniqueCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeAggregateHLLPPUniqueCount.
func (in *TypeAggregateHLLPPUniqueCount) DeepCopy() *TypeAggregateHLLPPUniqueCount {
	if in == nil {
		return nil
	}
	out := new(TypeAggregateHLLPPUniqueCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeAggregateHllppUniqueCount) DeepCopyInto(out *TypeAggregateHllppUniqueCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeAggregateHllppUniqueCount.
func (in *TypeAggregateHllppUniqueCount) DeepCopy() *TypeAggregateHllppUniqueCount {
	if in == nil {
		return nil
	}
	out := new(TypeAggregateHllppUniqueCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeAggregateMax) DeepCopyInto(out *TypeAggregateMax) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeAggregateMax.
func (in *TypeAggregateMax) DeepCopy() *TypeAggregateMax {
	if in == nil {
		return nil
	}
	out := new(TypeAggregateMax)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeAggregateMin) DeepCopyInto(out *TypeAggregateMin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeAggregateMin.
func (in *TypeAggregateMin) DeepCopy() *TypeAggregateMin {
	if in == nil {
		return nil
	}
	out := new(TypeAggregateMin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeAggregateSum) DeepCopyInto(out *TypeAggregateSum) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeAggregateSum.
func (in *TypeAggregateSum) DeepCopy() *TypeAggregateSum {
	if in == nil {
		return nil
	}
	out := new(TypeAggregateSum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeArray) DeepCopyInto(out *TypeArray) {
	*out = *in
	if in.ElementType != nil {
		in, out := &in.ElementType, &out.ElementType
		*out = new(Type)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeArray.
func (in *TypeArray) DeepCopy() *TypeArray {
	if in == nil {
		return nil
	}
	out := new(TypeArray)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeBool) DeepCopyInto(out *TypeBool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeBool.
func (in *TypeBool) DeepCopy() *TypeBool {
	if in == nil {
		return nil
	}
	out := new(TypeBool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeBytes) DeepCopyInto(out *TypeBytes) {
	*out = *in
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(TypeBytesEncoding)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeBytes.
func (in *TypeBytes) DeepCopy() *TypeBytes {
	if in == nil {
		return nil
	}
	out := new(TypeBytes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeBytesEncoding) DeepCopyInto(out *TypeBytesEncoding) {
	*out = *in
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = new(TypeBytesEncodingRaw)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeBytesEncoding.
func (in *TypeBytesEncoding) DeepCopy() *TypeBytesEncoding {
	if in == nil {
		return nil
	}
	out := new(TypeBytesEncoding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeBytesEncodingRaw) DeepCopyInto(out *TypeBytesEncodingRaw) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeBytesEncodingRaw.
func (in *TypeBytesEncodingRaw) DeepCopy() *TypeBytesEncodingRaw {
	if in == nil {
		return nil
	}
	out := new(TypeBytesEncodingRaw)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeDate) DeepCopyInto(out *TypeDate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeDate.
func (in *TypeDate) DeepCopy() *TypeDate {
	if in == nil {
		return nil
	}
	out := new(TypeDate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeFloat32) DeepCopyInto(out *TypeFloat32) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeFloat32.
func (in *TypeFloat32) DeepCopy() *TypeFloat32 {
	if in == nil {
		return nil
	}
	out := new(TypeFloat32)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeFloat64) DeepCopyInto(out *TypeFloat64) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeFloat64.
func (in *TypeFloat64) DeepCopy() *TypeFloat64 {
	if in == nil {
		return nil
	}
	out := new(TypeFloat64)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeInt64) DeepCopyInto(out *TypeInt64) {
	*out = *in
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(TypeInt64Encoding)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeInt64.
func (in *TypeInt64) DeepCopy() *TypeInt64 {
	if in == nil {
		return nil
	}
	out := new(TypeInt64)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeInt64Encoding) DeepCopyInto(out *TypeInt64Encoding) {
	*out = *in
	if in.BigEndianBytes != nil {
		in, out := &in.BigEndianBytes, &out.BigEndianBytes
		*out = new(TypeInt64EncodingBigEndianBytes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeInt64Encoding.
func (in *TypeInt64Encoding) DeepCopy() *TypeInt64Encoding {
	if in == nil {
		return nil
	}
	out := new(TypeInt64Encoding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeInt64EncodingBigEndianBytes) DeepCopyInto(out *TypeInt64EncodingBigEndianBytes) {
	*out = *in
	if in.BytesType != nil {
		in, out := &in.BytesType, &out.BytesType
		*out = new(TypeBytes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeInt64EncodingBigEndianBytes.
func (in *TypeInt64EncodingBigEndianBytes) DeepCopy() *TypeInt64EncodingBigEndianBytes {
	if in == nil {
		return nil
	}
	out := new(TypeInt64EncodingBigEndianBytes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeMap) DeepCopyInto(out *TypeMap) {
	*out = *in
	if in.KeyType != nil {
		in, out := &in.KeyType, &out.KeyType
		*out = new(Type)
		(*in).DeepCopyInto(*out)
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(Type)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeMap.
func (in *TypeMap) DeepCopy() *TypeMap {
	if in == nil {
		return nil
	}
	out := new(TypeMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeString) DeepCopyInto(out *TypeString) {
	*out = *in
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(TypeStringEncoding)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeString.
func (in *TypeString) DeepCopy() *TypeString {
	if in == nil {
		return nil
	}
	out := new(TypeString)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeStringEncoding) DeepCopyInto(out *TypeStringEncoding) {
	*out = *in
	if in.Utf8Raw != nil {
		in, out := &in.Utf8Raw, &out.Utf8Raw
		*out = new(TypeStringEncodingUtf8Raw)
		**out = **in
	}
	if in.Utf8Bytes != nil {
		in, out := &in.Utf8Bytes, &out.Utf8Bytes
		*out = new(TypeStringEncodingUtf8Bytes)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeStringEncoding.
func (in *TypeStringEncoding) DeepCopy() *TypeStringEncoding {
	if in == nil {
		return nil
	}
	out := new(TypeStringEncoding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeStringEncodingUtf8Bytes) DeepCopyInto(out *TypeStringEncodingUtf8Bytes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeStringEncodingUtf8Bytes.
func (in *TypeStringEncodingUtf8Bytes) DeepCopy() *TypeStringEncodingUtf8Bytes {
	if in == nil {
		return nil
	}
	out := new(TypeStringEncodingUtf8Bytes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeStringEncodingUtf8Raw) DeepCopyInto(out *TypeStringEncodingUtf8Raw) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeStringEncodingUtf8Raw.
func (in *TypeStringEncodingUtf8Raw) DeepCopy() *TypeStringEncodingUtf8Raw {
	if in == nil {
		return nil
	}
	out := new(TypeStringEncodingUtf8Raw)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeStruct) DeepCopyInto(out *TypeStruct) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]TypeStructField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeStruct.
func (in *TypeStruct) DeepCopy() *TypeStruct {
	if in == nil {
		return nil
	}
	out := new(TypeStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeStructField) DeepCopyInto(out *TypeStructField) {
	*out = *in
	if in.FieldName != nil {
		in, out := &in.FieldName, &out.FieldName
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(Type)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeStructField.
func (in *TypeStructField) DeepCopy() *TypeStructField {
	if in == nil {
		return nil
	}
	out := new(TypeStructField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeTimestamp) DeepCopyInto(out *TypeTimestamp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeTimestamp.
func (in *TypeTimestamp) DeepCopy() *TypeTimestamp {
	if in == nil {
		return nil
	}
	out := new(TypeTimestamp)
	in.DeepCopyInto(out)
	return out
}
