#!/bin/bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}/dev/tools/controllerbuilder

compileOut=$(go run ${REPO_ROOT}/cmd/manager/main.go 2>&1) || true

if [[ -z "${PROTO:-}" ]]; then
  echo "PROTO must be set. e.g. google.bigtable.admin.v2.Table"
  exit 1
fi


output=$(go run . prompt --src-dir="${REPO_ROOT}" --proto-dir="${REPO_ROOT}/dev/tools/proto-to-mapper/third_party/googleapis/" --output="${REPO_ROOT}/.generate" <<EOF
// +kcc:proto=${PROTO} 
// +kcc:no-compile-error=${compileOut}
EOF
2>&1)

last_line="${output##*$'\n'}"

echo "Output is cached to $last_line"
mv ${last_line} ${last_line}-${PROTO,,}-compile

# TODO: auto build dest-file based on PROTO and KIND
while read line
do
  echo "$line"
done < "${1:-/dev/stdin}"

go run . apply --src-file="${last_line}-${PROTO,,}-compile" --dest-file=${1}
