apiVersion: v1
data:
  cnrm.controller: gcr.io/gke-release/cnrm/cnrm/controller:2fa0f72
  cnrm.deletiondefender: gcr.io/gke-release/cnrm/cnrm/deletiondefender:2fa0f72
  cnrm.recorder: gcr.io/gke-release/cnrm/cnrm/recorder:2fa0f72
  cnrm.unmanageddetector: gcr.io/gke-release/cnrm/cnrm/unmanageddetector:2fa0f72
  cnrm.webhook: gcr.io/gke-release/cnrm/cnrm/webhook:2fa0f72
  prom-to-sd: gcr.io/gke-release/prometheus-to-sd:v0.11.12-gke.11
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/image-map: Images deployed by operator
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    cnrm.cloud.google.com/operator-system: "true"
  name: config-images
  namespace: configconnector-operator-system
